<Project Sdk="Microsoft.NET.Sdk">

  <!-- <ItemGroup>
    <Reference Include="ProcessMemory">
      <HintPath>..\libs\ProcessMemory32.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup> -->

  <ItemGroup>
    <PackageReference Include="NetMQ" Version="4.0.1.13" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="YamlDotNet" Version="13.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);CS8632</NoWarn>
    <!-- <PlatformTarget>x86</PlatformTarget> -->
  </PropertyGroup>

</Project>
